M48
; DRILL file {KiCad 7.0.1} date Wed Nov  8 23:04:46 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-11-08T23:04:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
%
G90
G05
T1
X103890Y-80130
X103890Y-82130
X103890Y-84130
X103890Y-86130
T0
M30
